install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_Linux-ARM64.deb
- sudo dpkg -i hugo*.deb
- hugo version
before_script:
- rm -rf public
script:
- hugo
branches:
  only:
  - master
